server:
  port: 7090
spring:
  application:
    name: msvc-videogames
  datasource:
    url: jdbc:mysql://localhost:3306/microservicio_videogame
    username: root
    password: Brian123
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update

eureka:
  instance:
    hostname: msvc-eureka
  client:
    service-url:
      defaultZone: http://localhost:7095/eureka

