server:
  port: 7095
spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: msvc-eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/