server:
  port: 7070
spring:
  application:
    name: msvc-gateway

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: true
    server-url:
      defaultZone: http://msvc-eureka:${server.port}/eureka/

gateway:
  global: /api/v1
  videoGames: /videogames
  promotion: /promotion
  categories: /categories
  platforms: /platforms
  shop: /shop
  stock: /stock
  videoGamesService: http://localhost:7090
  categoriesService: http://localhost:7091
  shopService: http://localhost:7092

security:
  user: user
  password: BEL-GamesShop